export const columns = [
  { id: "CaseId", label: "Case Id", minWidth: 170 },
  { id: "Vendor", label: "Vendor", minWidth: 100 },
  {
    id: "AssignedTo",
    label: "Assigned To",
    minWidth: 170,
  },
  {
    id: "Amount",
    label: "Amount",
    minWidth: 170,
  },
  {
    id: "DueDate",
    label: "Due Date",
    minWidth: 170,
  },
  ,
  {
    id: "Status",
    label: "Status",
    minWidth: 170,
  },
  {
    id: "Notes",
    label: "Notes",
    minWidth: 170,
  },
];

export const rows = [
  {
    CaseId: "CASE-001",
    Vendor: "Tech Solutions Inc",
    AssignedTo: "John Smith",
    Amount: 5250,
    DueDate: "2024-02-15",
    Status: "Pending",
    Notes: "Initial consultation completed",
  },
  {
    CaseId: "CASE-002",
    Vendor: "Digital Services Ltd",
    AssignedTo: "Sarah Johnson",
    Amount: 3800,
    DueDate: "2024-02-20",
    Status: "In Progress",
    Notes: "Awaiting client feedback",
  },
  {
    CaseId: "CASE-003",
    Vendor: "Innovation Corp",
    AssignedTo: "Mike Davis",
    Amount: 7500,
    DueDate: "2024-02-25",
    Status: "Completed",
    Notes: "Project delivered successfully",
  },
  {
    CaseId: "CASE-004",
    Vendor: "Global Systems",
    AssignedTo: "Lisa Wilson",
    Amount: 2100,
    DueDate: "2024-03-01",
    Status: "Pending",
    Notes: "Contract review in progress",
  },
  {
    CaseId: "CASE-005",
    Vendor: "Future Tech",
    AssignedTo: "Robert Brown",
    Amount: 9200,
    DueDate: "2024-03-05",
    Status: "In Progress",
    Notes: "Development phase ongoing",
  },
  {
    CaseId: "CASE-006",
    Vendor: "Smart Solutions",
    AssignedTo: "Emily Taylor",
    Amount: 4350,
    DueDate: "2024-03-10",
    Status: "Pending",
    Notes: "Awaiting approval",
  },
  {
    CaseId: "CASE-007",
    Vendor: "Advanced Systems",
    AssignedTo: "David Miller",
    Amount: 6750,
    DueDate: "2024-03-15",
    Status: "Completed",
    Notes: "Final testing completed",
  },
  {
    CaseId: "CASE-008",
    Vendor: "Tech Partners",
    AssignedTo: "Jennifer Lee",
    Amount: 3200,
    DueDate: "2024-03-20",
    Status: "In Progress",
    Notes: "Implementation phase",
  },
];
